org.gradle.jvmargs=-Xmx4048M

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=simplybows
mod_version=0.1.4
maven_group=net.sweenus

architectury_version=9.0.8

fabric_loader_version=0.15.11
fabric_api_version=0.88.1+1.20.1

forge_version=1.20.1-47.1.1

yarn_mappings=1.20.1+build.8

fzz_config_version=0.7.6+1.20.1
fzz_config_forge_version=0.7.6+1.20.1+forge
kotlinforforge_version=4.11.0
tomlkt_version=0.3.7
