modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Timefall Development License 1.2"

[[mods]]
modId = "simplybows"
version = "${version}"
displayName = "Simply Bows Reforged"
authors = "Sweenus, Hootea"
description = '''

'''
logoFile = "assets/simplybows/icon.png"

[[dependencies.simplybows]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplybows]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplybows]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simplybows]]
modId = "simplytooltips"
type = "required"
versionRange = "[0.1.4,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "simplybows.mixins.json"
