modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/oNxZero/simplybows/issues"
license = "Timefall Development License 1.2"

[[mods]]
modId = "simplybows"
version = "${version}"
displayName = "Simply Bows Reforged"
authors = "Sweenus, Hootea, oNxZero"
description = '''
Six elemental bows, four runes, and upgradeable strings and frames. Simply Bows Reforged is a maintained fork of Simply Bows by Sweenus and Hootea.
'''
logoFile = "assets/simplybows/logo.png"
displayURL = "https://github.com/oNxZero/simplybows"

[[dependencies.simplybows]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplybows]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplybows]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simplybows]]
modId = "simplytooltips"
type = "required"
versionRange = "[0.1.4,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "simplybows.mixins.json"
